### ISSUE TITLE
task instance is null or host is null

### ISSUE THREAD

**Issue by calury** [apache/dolphinscheduler-sdk-python#101]
3.1.6版本，正常生成工作流，资源列表为空，手动指定资源运行后，任务没有启动，日志显示为“任务实例host为空”

**Comment by zhongjiajie** [comment]
same as https://github.com/apache/dolphinscheduler-sdk-python/pull/99

**Comment by calury** [comment]
{"code":10000,"msg":"服务端异常: task instance is null or host is null","data":null,"failed":true,"success":false}

**Comment by calury** [comment]
按#99修改代码后安装PyDs包后，同样的流程，报:{"code":10000,"msg":"服务端异常: task instance is null or host is null","data":null,"failed":true,"success":false}

**Comment by zhongjiajie** [comment]
hi @calury this issue already fix in #116 and we will release it within 3 days, thanks for your bug reports
