### ISSUE TITLE
Set global variables

### ISSUE THREAD

**Issue by DaHanII** [apache/dolphinscheduler-sdk-python#102]
I can set global variables for single workflow on Web UI, but when I read pydolphinscheduler document I cannot find any place to show me how to set the global variables. Any idea on this question?
<img width="603" alt="image" src="https://github.com/apache/dolphinscheduler-sdk-python/assets/5406218/cc52b8f7-fece-4de6-943e-b3ed86361b7c">

**Comment by zhongjiajie** [comment]
please try to use `param` arg in `workflow` object, see more detail in https://dolphinscheduler.apache.org/python/main/_modules/pydolphinscheduler/core/workflow.html#Workflow

**Comment by DaHanII** [comment]
Thanks
