### ISSUE TITLE
Inconsistency between PyDolphinScheduler document and dolphinscheduler web

### ISSUE THREAD

**Issue by DaHanII** [apache/dolphinscheduler-sdk-python#103]
Hey, I find this inconsistency when I try to update the schedule of my workflow to dolphinscheduler web, which the document says 0 to 6 represents Sunday to Saturday (here I want to set it Monday to execute and I should set 1 here)
![image](https://github.com/apache/dolphinscheduler-sdk-python/assets/5406218/c4795ee9-a9ae-4048-8f76-c4cf6fd2589a) 
while in dolphinscheduler web I have to set it 2 to do that in my python code.
![image](https://github.com/apache/dolphinscheduler-sdk-python/assets/5406218/c44c9821-3095-4719-b51c-af5cdbfcccc4)
So I am curious about whether the PyDolphinScheduler document here is incorrect, where I find 1 to 7 actually represents Sunday to Saturday.

**Comment by zhongjiajie** [comment]
Thanks @DaHanII I update the doc in #104
