### ISSUE TITLE
Cannot find place to set task group id for tasks

### ISSUE THREAD

**Issue by DaHanII** [apache/dolphinscheduler-sdk-python#106]
I want to set task_group_id for each task in a single project for limiting concurrent executing task instances. But I cannot find any place  to set this task_group_id even I find it in the database. So Any idea on how to set it
![image](https://github.com/apache/dolphinscheduler-sdk-python/assets/5406218/d0845b74-6ace-4357-ae56-43c317f98ae3)

**Comment by zhongjiajie** [comment]
it seems we do not have task group for pydolphinscheduler yet

**Comment by DaHanII** [comment]
Hey, I find a place to set task group id when I get my workflow api response. It's task_definition_json in Workflow class, but the source code have not provided this variable setting yet. So I have to override Workflow class and task_definition_json method, where task_group_id is an optional parameter and give each task taskGroupId and its value in its dict. I hope this may help and I am looking forward to see this issue would be solved in the future.
![image](https://github.com/apache/dolphinscheduler-sdk-python/assets/5406218/283536a4-f983-44de-b326-4e57fdaec44f)

**Comment by zhongjiajie** [comment]
> Hey, I find a place to set task group id when I get my workflow api response. It's task_definition_json in Workflow class, but the source code have not provided this variable setting yet. So I have to override Workflow class and task_definition_json method, where task_group_id is an optional parameter and give each task taskGroupId and its value in its dict. I hope this may help and I am looking forward to see this issue would be solved in the future.
> ![image](https://user-images.githubusercontent.com/5406218/268894273-283536a4-f983-44de-b326-4e57fdaec44f.png)

we will add it in version 4.0.4
