### ISSUE TITLE
How to apply variables in clickhouse sql Task db

### ISSUE THREAD

**Issue by liusy-bd** [apache/dolphinscheduler-sdk-python#121]
<img width="455" alt="a2e66c54aac2157acffed010b839d49" src="https://github.com/apache/dolphinscheduler-sdk-python/assets/69708156/a273b958-60d0-47c6-a77e-4204a075bf50">
<img width="586" alt="39dbcdc9276f4df57c7a461b76f807c" src="https://github.com/apache/dolphinscheduler-sdk-python/assets/69708156/fc2afa3e-0e4e-4ce2-9f7c-bbac5f065689">
<img width="1920" alt="472b164f8dff947a5b0514dc99945e5" src="https://github.com/apache/dolphinscheduler-sdk-python/assets/69708156/fb9b1f53-ff2a-4f5b-ba4a-f598b5dc3913">
<img width="933" alt="1702965038870" src="https://github.com/apache/dolphinscheduler-sdk-python/assets/69708156/ae742791-1372-4f96-a5b3-6b40329d210d">

<img width="1162" alt="d67476a601b173820cab9b669eaaf15" src="https://github.com/apache/dolphinscheduler-sdk-python/assets/69708156/3a585f7b-e671-448e-a575-d16173709b8f">

<img width="1112" alt="1702964277536" src="https://github.com/apache/dolphinscheduler-sdk-python/assets/69708156/07cabe3b-bd88-46fa-8d95-faf76ac6f3a0">

For example, I output the variable env: test in test_para, but in the ods sql task it becomes 'test' with double quotes

**Comment by liusy-bd** [comment]
<img width="1139" alt="1702965379933" src="https://github.com/apache/dolphinscheduler-sdk-python/assets/69708156/746114bc-2cfd-4e3d-b9ad-6d3a98f554a4">

hive sql also reports errors

**Comment by zhongjiajie** [comment]
hi @liusy-bd it seem not related to sdk but dolphinscheduler itself. Which version do you use in this case?

**Comment by liusy-bd** [comment]
> 你好@liusy-bd它似乎与sdk无关，而是dolphinscheduler本身。在这种情况下您使用哪个版本？

ds :3.1.8
pyds: 4.0.4

Do you have any ideas?

**Comment by zhongjiajie** [comment]
> > 你好@liusy-bd它似乎与sdk无关，而是dolphinscheduler本身。在这种情况下您使用哪个版本？
> 
> ds :3.1.8 pyds: 4.0.4
> 
> Do you have any ideas?

I had check the related version, seems dolphinscheduler can not replace the table name and some of field name correctly. Could you add an issue to apache/dolphinscheduler?

**Comment by liusy-bd** [comment]
> > > 你好@liusy-bd它与 sdk 关联，而 dolphinscheduler 似乎本身。在这种情况下您使用哪个版本？
> > 
> > 
> > ds：3.1.8 pyds：4.0.4
> > 你有什么想法？
> 
> 我检查了相关版本，似乎dolphinscheduler无法正确替换表名和一些字段名。您可以向 apache/dolphinscheduler 添加问题吗？

Updated to dolphinscheduler！！！

https://github.com/apache/dolphinscheduler/issues/15457

**Comment by fuchanghai** [comment]
hi @liusy-bd  maybe we can use ```!{}```  #15238 cc @zhongjiajie

**Comment by zhongjiajie** [comment]
> hi @liusy-bd maybe we can use `!{}` #15238 cc @zhongjiajie

Got it and thanks for you clarification, cc @liusy-bd and I would like to close this issue
