### ISSUE TITLE
[bug] Can not set schedule publish status to online

### ISSUE THREAD

**Issue by MyColorfulDays** [apache/dolphinscheduler-sdk-python#71]
How to set schedule publish status to online
![image](https://user-images.githubusercontent.com/21351745/217752830-2a8ae14e-bbc8-4bee-b123-32ed3a87f46a.png)

**Comment by zhongjiajie** [comment]
can you share your version?

**Comment by MyColorfulDays** [comment]
dolphinscheduler version: 3.1.2
apache-dolphinscheduler version: 4.0.0

**Comment by zhongjiajie** [comment]
well, the good new is the patch from pr https://github.com/apache/dolphinscheduler/pull/13301 already release, but the bad new is we released in version 3.1.3, which you can see in https://github.com/apache/dolphinscheduler/releases/tag/3.1.3

**Comment by zhongjiajie** [comment]
Because version 3.1.3 is a bugfix version for 3.1.2 do you mind upgrading to solve this issue?

**Comment by MyColorfulDays** [comment]
Ok, is it possible to add a parameter for python sdk to control this state?

**Comment by zhongjiajie** [comment]
Currently, we have hidden logic for schedule time, when you do assign value to `workflow.schedule`, will create a workflow but the state of `schedule` is offline(it is without schedule). but if you assign the value to `workflow.schedule` we will create schedule connected to workflow and set it online default.

I am not sure wether this logic can help you or not

https://github.com/apache/dolphinscheduler/blob/3.1.3/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/python/PythonGateway.java#L272-L274

**Comment by MyColorfulDays** [comment]
Well, I see.

I think using a parameter, such as `schedule_pulish_stauts` or `schedule_online`,  to control it is more pythonic,  because explicit is better than implicit from the zen of python, and it compatible old versions.

Just sharing my opinion for your reference.

Thank you for your replay, and I know how to solve my problem now.

**Comment by zhongjiajie** [comment]
I reopen this issue for discussion
