### ISSUE TITLE
createOrUpdateWorkflow does not exist

### ISSUE THREAD

**Issue by yangzhiyuss** [apache/dolphinscheduler-sdk-python#79]
dolphinscheduler version: 3.1.4 
pydolphinscheduler version: 4.0.1
problem:
py4j.protocol.Py4JError: An error occurred while calling t.createOrUpdateWorkflow. Trace:
py4j.Py4JException: Method createOrUpdateWorkflow([class java.lang.String, class java.lang.String, class java.lang.String, class java.lang.String, class java.lang.String, class java.lang.String, class java.lang.String, class java.lang.Integer, class java.lang.Integer, class java.lang.String, class java.lang.Integer, class java.lang.String, class java.lang.String, null, class java.lang.String]) does not exist
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:318)
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:326)
	at py4j.Gateway.invoke(Gateway.java:274)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by yangzhiyuss** [comment]
One parameter is missing, adding this parameter succeeds

**Comment by yidigo** [comment]
which parameter should i add?

**Comment by zhongjiajie** [comment]
will take a look, and if true will release the new version ASAP

**Comment by yangzhiyuss** [comment]
> will take a look, and if true will release the new version ASAP

![image](https://user-images.githubusercontent.com/28888024/225548894-d6cb40de-d8b2-4022-9e63-57f32a687789.png)

**Comment by yangzhiyuss** [comment]
> will take a look, and if true will release the new version ASAP

![image](https://user-images.githubusercontent.com/28888024/225548967-5711d3db-d500-4acb-a08d-70f2337a8e36.png)


> which parameter should i add?

![image](https://user-images.githubusercontent.com/28888024/225549035-7d017735-ee6a-4db1-9a88-8c1445cc1eb0.png)

**Comment by zhongjiajie** [comment]
also fix https://github.com/apache/dolphinscheduler-sdk-python/issues/78, thanks for your report @yangzhiyuss

**Comment by zhongjiajie** [comment]
BTW, your project https://github.com/yangzhiyuss/sync_dolphinscheduler_resource like interesting, do you already use pydolphinscheduler in production?

**Comment by yangzhiyuss** [comment]
> BTW, your project https://github.com/yangzhiyuss/sync_dolphinscheduler_resource like interesting, do you already use pydolphinscheduler in production?
yes, File uploading and workflow submission have been fully automated through PyDolphinScheduler.

**Comment by zhongjiajie** [comment]
> BTW, your project https://github.com/yangzhiyuss/sync_dolphinscheduler_resource like interesting, do you already use pydolphinscheduler in production?
> yes, File uploading and workflow submission have been fully automated through PyDolphinScheduler.

@yangzhiyuss  looking good, do you want to share the usage of pydolphinscheduler?

**Comment by yangzhiyuss** [comment]
可以啊，可以做个中文分享
