### ISSUE TITLE
PyDolphinScheduler  An error occurred while calling t.createOrUpdateResource.

### ISSUE THREAD

**Issue by Capricorn0010** [apache/dolphinscheduler-sdk-python#93]
PyDolphinScheduler 执行上传资源总是提示An error occurred while calling t.createOrUpdateResource.
![image](https://github.com/apache/dolphinscheduler-sdk-python/assets/54889571/9219cd38-1cf3-41a5-9700-71d6d1dce5fe)

**Comment by zhongjiajie** [comment]
which version do you use?

**Comment by lycanthropes** [comment]
I also met this problem. And the version of my pydolphinscheduler is 4.0.3, and dolphinscheduler is 3.1.5. Besides, my OS is ubuntu 22.10. I just swicthed jdk to jdk 1.8.0, and it still don't work.

**Comment by baratamavinash225** [comment]
There can be a chance that if the workflow is already created and existing with the different user. And you are trying to re-create again with different user.
If it exists, then it has to be deleted or re-created with the same user.

**Comment by zhongjiajie** [comment]
> There can be a chance that if the workflow is already created and existing with the different user. And you are trying to re-create again with different user.
> If it exists, then it has to be deleted or re-created with the same user.

Yeah, probably the resource already exists, than you change the tenant and try to reupload it. Retry after you delete the resource

**Comment by zhongjiajie** [comment]
or maybe it related to https://github.com/apache/dolphinscheduler-sdk-python/issues/101?
